name = "proxy-client"
main = "index.js"
compatibility_date = "2023-09-01"

# 开发配置
[dev]
port = 8787

# 兼容模式
compatibility_flags = []

# KV命名空间绑定
[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "xxxx" # 替换为你的KV命名空间ID
preview_id = "xxxx" # 替换为你的预览KV命名空间ID

# 环境变量
[vars]
DEBUG_MODE = "false"

# 生产环境配置
[env.production]
# 此处应替换为实际的环境变量值
vars = { SERVICE_CONFIG_URL = "https://proxy-server.example.workers.dev", SERVICE_KEY = "example-service", UPDATE_INTERVAL = "3600" }
# SECRET_KEY变量应通过 `wrangler secret put SECRET_KEY` 命令设置，不要在此文件中明文存储

# 测试环境配置
[env.staging]
vars = { SERVICE_CONFIG_URL = "https://proxy-server-staging.example.workers.dev", SERVICE_KEY = "staging-service", UPDATE_INTERVAL = "1800" } 