name = "cloudflare-workers-proxy-client"
compatibility_date = "2023-09-01"
compatibility_flags = []

# Pages 配置
pages_build_output_dir = "./"

# KV命名空间绑定（客户端缓存）
[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "xxxx" # 需要替换为你的KV命名空间ID
preview_id = "xxxx" # 需要替换为你的预览KV命名空间ID

# 环境变量
[vars]
DEBUG_MODE = "false"

# 生产环境配置
[env.production]
vars = { 
    DEBUG_MODE = "false"
}
# 客户端环境变量（通过 Cloudflare Dashboard 或 wrangler secret 设置）：
# SERVER_URL - 服务端API地址（可选，如果设置则从服务端获取配置）
# SECRET_KEY - 访问服务端的密钥（当使用SERVER_URL时必需）
# SERVICE_KEY - 服务标识（当使用SERVER_URL时必需）
# PROXY_URL - 直接配置代理目标地址（当不使用SERVER_URL时必需）
# UPDATE_INTERVAL - 配置更新间隔（可选，默认3600秒）

# 测试环境配置
[env.staging]
vars = { 
    DEBUG_MODE = "true"
} 