name = "cloudflare-workers-proxy-client"
compatibility_date = "2023-09-01"
compatibility_flags = []

# Pages 配置
pages_build_output_dir = "./"

# KV命名空间绑定（客户端缓存）
# 通过环境变量 PROXY_CACHE_KV_ID 和 PROXY_CACHE_KV_PREVIEW_ID 配置
# 如果不设置KV，将使用其他配置方式（环境变量、服务端API）

# 环境变量
[vars]
DEBUG_MODE = "false"

# 生产环境配置
[env.production]
vars = { 
    DEBUG_MODE = "false"
}
# 客户端环境变量（通过 Cloudflare Dashboard Pages 设置页面配置）：
# 
# === 方式一：从服务端获取配置（推荐） ===
# SERVER_URL - 服务端API地址
# SECRET_KEY - 访问服务端的密钥
# SERVICE_KEY - 服务标识
# 
# === 方式二：直接配置代理地址 ===
# PROXY_URL - 代理目标地址
# UPDATE_INTERVAL - 配置更新间隔（可选，默认3600秒）
# 
# === 方式三：使用KV存储（可选） ===
# PROXY_CACHE_KV_ID - KV命名空间ID（生产环境）
# PROXY_CACHE_KV_PREVIEW_ID - KV命名空间ID（预览环境）
# 
# === 其他配置 ===
# DEBUG_MODE - 调试模式（true/false，默认false）

# 测试环境配置
[env.staging]
vars = { 
    DEBUG_MODE = "true"
} 