name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cloudflare-workers-proxy-client
          directory: ./
          # Pages Functions 自动检测 _worker.js 文件
          # 环境变量在 Cloudflare Dashboard Pages 设置页面配置 